// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbuqklivzilobyaavwas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZidXFrbGl2emlsb2J5YWF2d2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDM2ODYsImV4cCI6MjA2NDM3OTY4Nn0.mSY64PZVJLi7364C2A0gRjWPK56SeIaxX8Rm_hjtizI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);